/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AgentRuns": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Alerts": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Bus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "Items": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Tasks": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}